apiVersion: v1
kind: Service
metadata:
  name: bank-mate-api-service
spec:
  selector:
    app: bank-mate-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  